app: rethinking_jepa.prepare_imagenet_probe_subset

subset:
  source: huggingface
  hf_repo_id: benjamin-paine/imagenet-1k-256x256
  hf_source_split: train
  output_root: data/imagenet_probe_related_subset
  action_classes:
    - abseiling
    - air drumming
    - applauding
    - archery
    - arm wrestling
  copy_mode: copy
  sample_seed: 0
  max_total_images: 10000
  val_fraction: 0.2

#

# Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
# Resolving data files: 100%|████████████████████████████████| 40/40 [00:00<00:00, 30278.32it/s]
# Resolving data files: 100%|████████████████████████████████| 40/40 [00:00<00:00, 75301.69it/s]
# imagenet probe subset prepared
# output_root: data/imagenet_probe_related_subset
# source: huggingface
# hf_repo_id: benjamin-paine/imagenet-1k-256x256
# hf_source_split: train
# max_total_images: 10000
# val_fraction: 0.2
# sample_seed: 0
# target_counts_per_class: {'alp': 589, 'barbell': 589, 'bow': 589, 'chime': 589, 'cliff': 588, 'cliff dwelling': 588, 'crash helmet': 588, 'drum': 588, 'dumbbell': 588, 'gong': 588, 'home theater': 588, 'maraca': 588, 'microphone': 588, 'mountain tent': 588, 'stage': 588, 'steel drum': 588, 'theater curtain': 588}
# copy_mode: copy
# related_imagenet_labels: ['alp', 'cliff', 'cliff dwelling', 'mountain tent', 'crash helmet', 'drum', 'steel drum', 'gong', 'maraca', 'microphone', 'stage', 'theater curtain', 'home theater', 'bow', 'barbell', 'dumbbell']
# train_counts:
#   alp: 471
#   barbell: 471
#   bow: 471
#   chime: 471
#   cliff: 470
#   cliff_dwelling: 470
#   crash_helmet: 470
#   drum: 470
#   dumbbell: 470
#   gong: 470
#   home_theater: 470
#   maraca: 470
#   microphone: 470
#   mountain_tent: 470
#   stage: 470
#   steel_drum: 470
#   theater_curtain: 470
# val_counts:
#   alp: 118
#   barbell: 118
#   bow: 118
#   chime: 118
#   cliff: 118
#   cliff_dwelling: 118
#   crash_helmet: 118
#   drum: 118
#   dumbbell: 118
#   gong: 118
#   home_theater: 118
#   maraca: 118
#   microphone: 118
#   mountain_tent: 118
#   stage: 118
#   steel_drum: 118
#   theater_curtain: 118
# totals: train=7994 val=2006 total=10000
# (venv) (base) samprasmanueldsouza@Samprass-MacBook-Pro-2 Playground % 